### ISSUE TITLE
DETR KeyError: 'axes' and KeyError: '_outputs'

### ISSUE THREAD

**Issue by ktobah** [nerox8664/onnx2keras#93]
I am trying to convert a DETR model from pytorch to Keras. The process has to parts:

1. From Pytorch to onnx
2. From onnx to keras

The first part works fine and for the second part (using your onnx2keras), I get errors like KeyError: 'axes' and KeyError: '_outputs'.
The part responsible for generating the params of the node is this:

`node_params = onnx_node_attributes_to_dict(node.attribute)`

I checked the node attributes, and they are not there. I was wondering if you can shed some light on why is this happening?

Thank you.

**Comment by Andredance** [comment]
Hi! Can you share your onnx model or tell more about layer that failed?

**Comment by ktobah** [comment]
The models are a bit large. However, here is the Github repo of DETR. 
https://github.com/facebookresearch/detr

It has pretrained Pytorch models links there. I used the resnet50 backbone. I used the following code to convert from Pytorch to onnx:

```
import torch
import torchvision.transforms as T
from torch.autograd import Variable
import onnx

# load DETR R50 with pretrained weights
model = torch.hub.load('facebookresearch/detr', 'detr_resnet50', pretrained=True)
model.eval()

dummy_input = Variable(torch.randn(1, 3, 800, 1777))

input_names=['input_image']
output_names=['pred_logits', 'pred_boxes']
dynamic_axes= {'input_image': {0: 'batch_size', 2: 'width', 3: 'height'}}

torch.onnx.export(model, dummy_input, "model.onnx", input_names=input_names, output_names=output_names,
                  dynamic_axes=dynamic_axes, verbose=1, opset_version=11)

# Load the ONNX file
model = onnx.load('model.onnx')
```

**Comment by Andredance** [comment]
Hi! I looked better at your problem and unfortunately, I have to say that there is no way to convert __detr__ models because of the following points:
1. Onnx export for __detr__ models works only with opset_version >= 11 where __onnx2keras__ supports mostly opset_version 9.
2. __Detr__ onnx model starts with __Gather__ operator for the input layer (which is a tf.Tensor) and we don't support __Gather__ for tf.Tensor since a lot of the following layers depends on numpy arrays.

Maybe it will be solved in the feature :)

**Comment by ktobah** [comment]
Alright, thank you very much for your time and explanation. I will close it for now, I guess.
